server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_booking?createDatabaseIfNotExist=true
    username: root
    password: 1299     # or your local MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT CONFIG
jwt:
  secret: ${JWT_SECRET:MY_SUPER_SECRET_KEY_123456789_ABCDEF_9876543210}
  expiration: 86400000   # 1 day

# AWS CONFIG (Using environment variables here)
aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  bucket: ${AWS_BUCKET:travel-booking-assets}
  region: ${AWS_REGION:ap-south-1}
